
#name:  $(GitVersion.NuGetVersion)
name: $(GitVersion.SemVer)

parameters:
- name: BuildConfiguration
  displayName: Release or Debug
  type: string
  default: Release
  values:
  - Release
  - Debug

resources:
- repo: self
  fetchDepth: 30

variables:
  BuildPlatform: 'Any CPU'
 # BuildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    variables:
      "Nuget.Feed": 'dct-pkg'  
      "Nuget.Version": '5.3.0'
      "DotnetCore.Version": '3.1.x'
      
    pool:
      name: DCT
      demands:
      #- TestBuildServer
      - IsBuildServer

    steps:

    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk : $(DotnetCore.Version)'
      inputs:
        packageType: sdk
        version: $(DotnetCore.Version)
        
#    - task: NuGetToolInstaller@0
#      displayName: 'Use NuGet : $(Nuget.Version)'
#      inputs:
#        versionSpec: '> $(Nuget.Version)'
#        checkLatest: true

    - task: UseGitVersion@5
      displayName: use Git Version to generate build number
      inputs:
        versionSpec: '5.x'

    - task: PowerShell@2
      name: DislayAllVariables2
      displayName: 'Display all variables'
      continueOnError: true  
      inputs:
        targetType: 'inline'
        script: |
            (gci env:*).GetEnumerator() | Sort-Object Name | ForEach {Write-Host "Name: $($_.Name) | Value : $($_.Value)"}

    # Generate the report using ReportGenerator (https://github.com/danielpalme/ReportGenerator)
    # First install the tool on the machine, then run it
    - script: |
            dotnet tool update dotnet-reportgenerator-globaltool --version 4.3.6  
      displayName: Install/update dotnet-reportgenerator-globaltool
      continueOnError: true  
      enabled: false

    - task: DotNetCoreCLI@2
      displayName: 'Restore Nuget packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
        vstsFeed: 'dct-pkg'

    - task: DotNetCoreCLI@2
      displayName: Build Projects
      inputs:
        workingDirectory: "$(Build.SourcesDirectory)/src/"
        projects: '**/*.csproj'
        command: build
        arguments: "--configuration ${{ parameters.BuildConfiguration }} --no-restore -p:version=$(Build.BuildNumber) -p:FileVersion=$(Build.BuildNumber)"

#********************************************************************************
# Copy Nuget Packages into Aftifact Folder before test.
#********************************************************************************   
    - task: CopyFiles@2
      displayName: 'Copy Nuget Interface Packages Files - Artifact NugetInterface Directory'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)/src'
        Contents: |
         **\*$(Build.Configuration)*\*Interface.nupkg
         !**\packages\**
         !**\bin\x64\**
        TargetFolder: '$(build.artifactstagingdirectory)\Nuget\Interface'
        CleanTargetFolder: true
        flattenFolders: true
    
    - task: CopyFiles@2
      displayName: 'Copy NugetPackages Files - Artifact NugetPackages Directory'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)\src'
        Contents: |
         **\${{ parameters.BuildConfiguration }}\*.nupkg
         !**\packages\**
         !**\bin\x64\**
        TargetFolder: '$(build.artifactstagingdirectory)\Nuget\Packages'
        CleanTargetFolder: true
        flattenFolders: true

        
#********************************************************************************
# Package Web Api
#********************************************************************************   

    - task: DotNetCoreCLI@2
      displayName: 'Package Api Artifact Folder'
      inputs:
        command: publish
        publishWebProjects: false
        zipAfterPublish: true
        nobuild: true
        projects: '**/*.FundingClaims.Api.csproj'
        arguments: '--configuration ${{ parameters.BuildConfiguration }} --no-build -p:version="$(Build.BuildNumber)" -p:FileVersion="$(Build.BuildNumber)" --output "$(Build.ArtifactStagingDirectory)\Web\API"'

      - task: DotNetCoreCLI@2
      displayName: 'Build WebJob - FundingClaim.Consol'
      inputs:
        command: publish
        configuration: '${{ parameters.BuildConfiguration }}'
        publishWebProjects: false
        zipAfterPublish: true
        nobuild: true
        projects: '**/*.FundingClaims.ReminderService.csproj'
        arguments: '--configuration ${{ parameters.BuildConfiguration }} --no-build -p:version="$(Build.BuildNumber)" -p:FileVersion="$(Build.BuildNumber)" --output "$(Build.SourcesDirectory)\tmp\app_Data\Jobs\Triggered\ESFA.DC.FundingClaim.ReminderService"'

    ## Create Zip File for Deployment     
    - task: ArchiveFiles@2
      displayName: 'Package WebJobs for Website'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)\tmp'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)\Web\WebJobs.zip'

#********************************************************************************
# SQL database Project Build and Acopy to  Artifact Directory
#********************************************************************************   
    - task: MSBuild@1
      enabled: true
      displayName: 'Build solution'
      inputs:
        solution: '**/ESFA.DC.FundingClaims.Database.sqlproj'
        configuration: '${{ parameters.BuildConfiguration }}'
        msbuildArguments: '-p:version=$(Build.BuildNumber) -p:FileVersion=$(Build.BuildNumber) -p:SkipInvalidConfigurations=true'
        clean: false
        maximumCpuCount: true
        restoreNugetPackages: false
        logProjectEvents: true
        createLogFile: true  
        
    - task: CopyFiles@2
      displayName: 'Copy Database Files - Artifact Databases Directory'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: |
         **\*.Database\**\*.dacpac
        TargetFolder: '$(build.artifactstagingdirectory)\Databases'
        CleanTargetFolder: true
        flattenFolders: true

#********************************************************************************
# Count Artifact Files to decide what to Publish
#********************************************************************************    
    - task: PowerShell@2
      enabled: true
      displayName: 'Check What to Publish'
      continueOnError: true  
      inputs:
        targetType: 'inline'
        script: |
                  Write-Host "##vso[task.setvariable variable=PublishArtifact_Web]$(Test-Path '$(build.artifactstagingdirectory)\Web' -PathType Any)";
                  Write-Host "##vso[task.setvariable variable=PublishArtifact_NugetPackages]$(Test-Path '$(build.artifactstagingdirectory)\Nuget' -PathType Any)";
                  Write-Host "##vso[task.setvariable variable=PublishArtifact_Databases]$(Test-Path '$(build.artifactstagingdirectory)\Databases' -PathType Any)";

#********************************************************************************
# Run Unit Tests
#********************************************************************************
    - task: DotNetCoreCLI@2
      displayName: 'Run xUnit Test - Core Framework'
      enabled: false
      inputs:
        command: test
        projects: 'src/*Tests/*.csproj'
        arguments: '--configuration $(Build.Configuration) --collect "Code coverage"'

        
#********************************************************************************
# Generate Code Coverage Report and Publish
#********************************************************************************
# need to add Nuget PAckage 'coverlet.msbuild' to  Test Projects.
#
     ## Generate the report using ReportGenerator (https://github.com/danielpalme/ReportGenerator)
    # First install the tool on the machine, then run it
    - script: |
          dotnet tool update -g dotnet-reportgenerator-globaltool --version 4.3.6  
          reportgenerator -reports:$(Build.SourcesDirectory)/**/*Tests/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:Cobertura
      displayName: Create Code coverage report
      enabled: false
  
    # Publish the code coverage result (summary and web site)
    # The summary allows to view the coverage percentage in the summary tab
    # The web site allows to view which lines are covered directly in Azure Pipeline
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage'
      enabled: false
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
        reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
      
#********************************************************************************
# Publish Artifacts
#********************************************************************************    

    ## Publish Web Artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Web'
      enabled: True
      condition: and(succeeded(), eq(variables['PublishArtifact_Web'], 'True'))
      inputs:
        ArtifactName: Web
        PathtoPublish: '$(build.artifactstagingdirectory)\Web'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: NugetPackages'
      enabled: True
      condition: and(succeeded(), eq(variables['PublishArtifact_NugetPackages'], 'True'))
      inputs:
        ArtifactName: NugetPackages
        PathtoPublish: '$(build.artifactstagingdirectory)\Nuget'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Databases'
      enabled: True
      condition: and(succeeded(), eq(variables['PublishArtifact_Databases'], 'True'))
      inputs:
        ArtifactName: Databases
        PathtoPublish: '$(build.artifactstagingdirectory)\Databases'
